### ISSUE TITLE
Credit to authors

### ISSUE THREAD

**Issue by peter227** [ki-ujep/facilities#37]
- doc. Orava řekl, že by rád abychom se tam uvedli do sekce about jako autoři, klidně s našimi fotkami
- domluvili jsme se, že fotky nám přijdou jako zbytečné, ale viděli bychom to formou nějakých prokliků na naše LinkedIN nebo github profily

**Comment by MQ37** [comment]
+ se zeptat i Beryho, zda nechce uvést (udělal základ webu)
