### ISSUE TITLE
Responzivita

### ISSUE THREAD

**Issue by peter227** [ki-ujep/facilities#47]
Aktuálně je web responzivní, ale vyskytují se tam některé problémy, které se ještě musí vyřešit. Konkrétně tyto:
- Na stránce about je problém s patičkou resp. s body. Nedá se scrollovat a tak není vidět konec stránky, kde je např. odkaz na github
- U detailu zařízení může přesahovat název kategorie (pokud je moc dlouhý) div card, to stejné se děje i v seznamu kategorií po rozkliknutí kategorie a zobrazení zařízení může přesahovat název kategorie v listu

**Comment by peter227** [comment]
[petr/responsiveness](https://github.com/ki-ujep/facilities/tree/petr/responsiveness)

**Comment by MQ37** [comment]
může se tato issue zavřít?
