### ISSUE TITLE
Partner organizations

### ISSUE THREAD

**Issue by peter227** [ki-ujep/facilities#65]
Aktuálně je možnost přidat zařízení pouze pod Ujep fakulty, doc. Orava vznesl požadavek zda bychom mohli nějak vyřešit, aby se dali přidat i organizace které nemají spojitost s Ujep např. Ustav anorganicke chemie.

**Comment by MQ37** [comment]
Vytvořeno PR https://github.com/ki-ujep/facilities/pull/66
